import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/header'
import { Toaster } from '@/components/ui/toaster'
import SidebarLayout from '@/components/layouts/sidebar-layout'
import { cn } from '@/lib/utils'

import '../globals.css'

const components: {
  index: string
  label: string
}[] = [
  {
    index: 'conversation-card',
    label: 'Conversation Card',
  },
  {
    index: 'chat-message',
    label: 'Chat message',
  },
  {
    index: 'job-card',
    label: 'Job Card',
  },
]

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  params: { locale: string }
  children: React.ReactNode
}>) {
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.className
        )}
      >
        <Header />
        <main className="">
          <SidebarLayout
            title="Components"
            sidebar="3"
            pages={components.map((item) => ({
              label: item.label,
              url: `/components/${item.index}`,
            }))}
          >
            {children}
          </SidebarLayout>
        </main>
        <Toaster />
      </body>
    </html>
  )
}
