import type { Metadata } from 'next'

import CommonWithHeaderLayout from '@/components/layout/with-header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default CommonWithHeaderLayout
