import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/layout/header'
import { Toaster } from '@/components/ui/toaster'

import { cn } from '@/lib/utils'
import { verifySession } from '@/lib/session'
import { getUserById } from '@/lib/endpoints/auth'

import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  params: { locale: string }
  children: React.ReactNode
}>) {
  const userId = await verifySession()

  let user

  if (userId) {
    const response = await getUserById({ id: userId })

    if (response.data) {
      user = response.data
    }
  }

  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.className
        )}
      >
        <Header user={user} />
        <main className="">{children}</main>
        <Toaster />
      </body>
    </html>
  )
}
